blank_issues_enabled: false
contact_links:
  - name: Question & Discussion
    url: https://github.com/femboypig/darwincode/discussions
    about: Ask questions or discuss features with the community.
